### ISSUE TITLE
Can not build with llvm-mingw

### ISSUE THREAD

**Issue by calvin2021y** [ForestDB-KVStore/forestdb#3]
I proposal to use libuv replace the local implement for diff platform.

For example uv_hrtime and uv_gettimeofday, this will made forestdb work on much more platform.

**Comment by greensky00** [comment]
Jungle officially does not support Windows yet. The original ForestDB [does support it](https://github.com/couchbase/forestdb/blob/master/src/arch.h), but this fork of ForestDB does not. And we abstain from adding dependencies to make the library compact and neat,

**Comment by calvin2021y** [comment]
thanks for explain.
